### PR TITLE
Upgrade cloudstate to 0.5.2. Generate protobufs on compile instead of…

### PR DESCRIPTION
**Pull request by sean-walsh**
… package.

### CODE REVIEW

**Review by olofwalker — APPROVED** [review]
LGTM. I assume this has been tested?

**Comment by viktorklang** [comment]
LGTM

**Comment by sean-walsh** [comment]
> LGTM. I assume this has been tested?

Yes, I ran mvn test, there were no it:tests.

**Comment by sean-walsh** [comment]
@pvlugter @viktorklang Peter (hello again) would you help me merge and publish as soon as you can? I'm porting my IoT demo to spring for Brad and Sushila.

**Comment by sleipnir** [comment]
Hello to the new ones here.
I always recommend using the build.sh file to validate the build and testing process

**Comment by sleipnir** [comment]
I ran the full build and also the tck against the generated docker image 0.5.2-wip_upgrade_cloudstate_0.5.2-SNAPSHOT and the TCK fails two tests due to recent changes in the TCK. I will be correcting this in the coming weeks so don't worry about it.

springboot

springboot-2

That said, the build and tests are successfully completed so I will merge the changes of this PR.
Thanks for the PR @sean-walsh

**Comment by sleipnir** [comment]
@sean-walsh About publishing in maven repo one things. It seems to me that the OSS credits on Travis for this repository are over and we need to check how to proceed manually @pvlugter  may help with that. 
I believe that for your presentation none of this is impeding or unavoidable

**Comment by pvlugter** [comment]
Yes, we're out of Travis credits. Not sure what the plan is — we have a CircleCI account as well, used by the main cloudstate repo. Or Github Actions has been discussed. I can publish a new version manually for now.

**Comment by pvlugter** [comment]
I've published version `0.5.2` manually

**Comment by viktorklang** [comment]
@pvlugter Would Github Actions work? @michaelpnash wdyt?

**Comment by sleipnir** [comment]
Thanks @pvlugter

**Comment by sleipnir** [comment]
Yes @viktorklang Since all the work is done by scripts it shouldn't be a problem to migrate it to Github Actions

**Comment by sleipnir** [comment]
@pvlugter I created Draft PR https://github.com/cloudstateio/springboot-support/pull/19 to work together on this, I need you to help me with repository passwords

**Pull request merged**
